sonar.sources=.
sonar.exclusions=node_modules/**,pip-cache/**,xdg-cache/**,apt-cache/**,sbcore/static/bundles/**,**/*coverage.xml
sonar.coverage.exclusions=**/*.js,**/integration/**,**/commands/**,**/admin_style/**,**/apps.py,**/admin.py
sonar.sourceEncoding=UTF-8